FILENAME=spisd.device
DIR=build-device-debug
OBJECTS=device.o spi-par.o spi-par-low.o sd.o timer.o

SRCDIRS=. ../common
INCDIRS=. ../common

EXTRA_CFLAGS=-ramiga-dev -DDEBUG=3
EXTRA_LDFLAGS=-ldebug

include ../common/common.mk
