# Must use the gcc 2.95 amiga toolchain for this. 
FILENAME=sdbox.device
DIR=build-device-debug
OBJECTS=device.o 

SRCDIRS=. 
INCDIRS=. 

EXTRA_CFLAGS=-ramiga-dev -DDEBUG 
EXTRA_LDFLAGS=-ldebug

include common.mk
